// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6g-zeC3AB77enxOoyoxQk-Hedm3meSPI',
    appId: '1:196055777836:web:223ce64ed633fe44298789',
    messagingSenderId: '196055777836',
    projectId: 'relaxmind43',
    authDomain: 'relaxmind43.firebaseapp.com',
    storageBucket: 'relaxmind43.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzVioxHZTBR8qtKov7ZNY1bmPf91XFY9U',
    appId: '1:196055777836:android:26c25699b603f6f4298789',
    messagingSenderId: '196055777836',
    projectId: 'relaxmind43',
    storageBucket: 'relaxmind43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR2WBb5eZ-WuSW7ctsSP5LYJAypU85kb0',
    appId: '1:196055777836:ios:5f4f674fcd314a06298789',
    messagingSenderId: '196055777836',
    projectId: 'relaxmind43',
    storageBucket: 'relaxmind43.firebasestorage.app',
    iosBundleId: 'com.example.relaxMind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR2WBb5eZ-WuSW7ctsSP5LYJAypU85kb0',
    appId: '1:196055777836:ios:5f4f674fcd314a06298789',
    messagingSenderId: '196055777836',
    projectId: 'relaxmind43',
    storageBucket: 'relaxmind43.firebasestorage.app',
    iosBundleId: 'com.example.relaxMind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6g-zeC3AB77enxOoyoxQk-Hedm3meSPI',
    appId: '1:196055777836:web:c4667f5c8b749918298789',
    messagingSenderId: '196055777836',
    projectId: 'relaxmind43',
    authDomain: 'relaxmind43.firebaseapp.com',
    storageBucket: 'relaxmind43.firebasestorage.app',
  );

}